[project]
name = "fourier-neural-operator"
version = "1.0.0"
description = "A PyTorch implementation of Fourier Neural Operator (FNO) for solving partial differential equations."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "lightning",
    "numpy",
    "pandas",
    "pillow",
    "scipy",
    "sympy",
    "tensorly",
    "torch",
    "torchaudio",
    "torchvision",
    "tqdm",
]

